name: Publish
on:
  push:
    tags:
      - "v*"
      - "beta-v*"
jobs:
  publish:
    runs-on: ${{ matrix.os }}

    env:
      working-directory: ./code/ClickerCompanion

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 19.3.0

      - name: Install and build
        working-directory: ${{env.working-directory}}
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Publish releases
        working-directory: ${{env.working-directory}}
        env:
          # # These values are used for auto updates signing
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --mac --linux
